---
functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Пользователь должен иметь возможность зарегистрироваться и авторизироваться на сайте
  - Пользователь должен иметь возможность игры с ботом 
  - После успешной авторизации, система должна сохранять сессию и запомнить пользавателя
  - Пользователь должен иметь возможность создания игры 
  - Пользователь должен иметь возможность приглашать в свою игру соперников
  - Пользователь должен иметь возможность выбора сложгости создаваемой игры
  - Пользователь должен иметь возможность подключения к уже созданой доступной игре
  - Пользователь должен иметь возможность отказаться от приглашения к игре 
  - Пользователь должен иметь возможность общения в чате с соперником во время игры 
  - Пользователь должен иметь возможность просматривать запись завершившихся игр на сайте
  - Игрок должен иметь возможность видеть решение соперника в реальном времени
  - Игрок должен иметь возможность проверить свое решение 
  - Игрок должен иметь возможность сдаться 
  - Игрок должен увидеть оповещение о выйгрыше/пройгрыше игры 
  - Игрок должен иметь возможность просмотреть запись своей игры 
  - На главной странице должен быть список всех пользователей, находящихся онлайн

non-functional: 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров

implict:
  - Пользователь должен иметь возможность ознакомиться с правилами игры на сайте
  - Пользователь должен иметь возможность переподключиться в игру, если вылетел с сайта 
  - Пользователь не может менять код после завершения игры
  - При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  - Пользователь должен иметь возможность выбора задания по категории


